name: R Tests

on:
  push:
    branches: [ main, master, develop, copilot/** ]
  pull_request:
    branches: [ main, master, develop ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        r-version: ['4.3.0']
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
    
    - name: Install R packages
      run: |
        Rscript INSTALL.R
    
    - name: Run tests
      run: |
        Rscript tests/run_tests.R
    
    - name: Test Summary
      if: always()
      run: |
        echo "✅ R tests completed!"
